# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				arrow = true
				cow = true
				chest_minecart = true
				pig = true
				pillager = true
				iron_golem = true
				skeleton = true
				bat = true
				cat = true
				zombie = true
				drowned = true
				guardian = true
				sheep = true
				experience_orb = true
				player = true
				stray = true
				item = true
				villager = true
				wolf = true
				skeleton_horse = true
				salmon = true
				tnt_minecart = true
				zombie_villager = true
				item_frame = true
				vindicator = true
				painting = true
				cave_spider = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				parrot = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.earthtojavamobs]
				bronzed_chicken = true
				muddy_foot_rabbit = true
				pinto_cow = true
				cookie_cow = true
				flecked_sheep = true
				cream_cow = true
				albino_cow = true
				umbra_cow = true
				jolly_llama = true
				mottled_pig = true
				muddy_pig = true
				inky_sheep = true
				tropical_slime = true
				pale_pig = true

			[light_sources.settings.entities.mobz]
				knight2 = true
				armored = true
				toad = true
				creep = true
				boar2 = true
				spi = true
				boar3 = true
				boar = true
				tspider = true
				fast = true
				brownbear = true
				spo = true
				slimo = true
				frost = true
				archer = true
				skeli2 = true
				friend = true
				knight = true
				skeli4 = true
				dwarf = true
				tank = true
				icegolem = true
				gchicken = true

			[light_sources.settings.entities.untitledduckmod]
				goose = true
				duck = true

			[light_sources.settings.entities.outvoted]
				glare = true

			[light_sources.settings.entities.phasmophobia]
				revenant = true

			[light_sources.settings.entities.squirrels]
				squirrel = true

			[light_sources.settings.entities.golemsgalore]
				obsidian_golem = true
				amethyst_golem = true
				laser_golem = true

